project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "data/"
    - "files/"
    - "handouts/"
    - "scripts/"
    - "!admin/"
    - "!archive/"
    - "!answer-keys/"

website:
  title: "EPsy 8252"
  navbar:
    background: "#ADCAD6"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      # - sidebar:assignments
      - text: "Assignments & Grading"
        file: assignments.qmd
      - text: "Data"
        file: data.qmd
      - text: "Class Policies"
        file: class-policies.qmd
      - text: "Instructor & TA"
        file: instructor.qmd
      - text: "Mission Statements"
        file: mission-statements.qmd
      - text: "University Policies"
        file: umn-policies.qmd
        
  # sidebar:
  #   - id: assignments
  #     title: "Assignments"
  #     style: "docked"
  #     background: light
  #     collapse-level: 1
  #     contents: 
        # - assignments.qmd
        # - assignments/assignment-01-introduction-to-quarto.qmd
        # - assignments/assignment-02-polynomial-effects.qmd
        # - assignments/assignment-03-evidence-and-model-selection.qmd
        # - assignments/assignment-04-logarithmic-transformations.qmd
        # - assignments/assignment-05-logistic-regression.qmd
        # - assignments/assignment-06-lmer-unconditional-longitudinal-models.qmd
        # - assignments/assignment-07-longitudinal-analysis-ii.qmd

format:
  html:
    theme: 
      - cosmo
      - "assets/theme.scss"
    css: ["assets/sticky-notes.css"]
    header-includes: |
      <script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    sidebar: false
    mainfont: 'Atkinson Hyperlegible'
    fontsize: '1.05em'
    linestretch: '1.5em'
    linkcolor: '#c10088'
    toc: true
    toc-title: "On This Page"
    


  
