<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-12-12">

<title>Likelihood: A Framework for Evidence – EPsy 8252</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-d3043699f4f525e226433170f63674df.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d20cc3c81b1b56bba6ca861840b10611.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/pagedtable/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable/js/pagedtable.js"></script>
<script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/sticky-notes.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">EPsy 8252</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html"> 
<span class="menu-text">Assignments &amp; Grading</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../class-policies.html"> 
<span class="menu-text">Class Policies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../instructor.html"> 
<span class="menu-text">Instructor &amp; TA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mission-statements.html"> 
<span class="menu-text">Mission Statements</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../umn-policies.html"> 
<span class="menu-text">University Policies</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On This Page</h2>
   
  <ul>
  <li><a href="#preparation" id="toc-preparation" class="nav-link active" data-scroll-target="#preparation">Preparation</a></li>
  <li><a href="#research-questions-and-modeling-strategy" id="toc-research-questions-and-modeling-strategy" class="nav-link" data-scroll-target="#research-questions-and-modeling-strategy">Research Questions and Modeling Strategy</a></li>
  <li><a href="#classical-framework-of-evidence" id="toc-classical-framework-of-evidence" class="nav-link" data-scroll-target="#classical-framework-of-evidence">Classical Framework of Evidence</a></li>
  <li><a href="#likelihood-paradigm-to-statistical-evidence" id="toc-likelihood-paradigm-to-statistical-evidence" class="nav-link" data-scroll-target="#likelihood-paradigm-to-statistical-evidence">Likelihood Paradigm to Statistical Evidence</a></li>
  <li><a href="#joint-probability-density-a-roadstop-to-computing-likelihood" id="toc-joint-probability-density-a-roadstop-to-computing-likelihood" class="nav-link" data-scroll-target="#joint-probability-density-a-roadstop-to-computing-likelihood">Joint Probability Density: A Roadstop to Computing Likelihood</a></li>
  <li><a href="#computing-likelihood" id="toc-computing-likelihood" class="nav-link" data-scroll-target="#computing-likelihood">Computing Likelihood</a>
  <ul class="collapse">
  <li><a href="#an-example-of-computing-and-evaluating-likelihood" id="toc-an-example-of-computing-and-evaluating-likelihood" class="nav-link" data-scroll-target="#an-example-of-computing-and-evaluating-likelihood">An Example of Computing and Evaluating Likelihood</a></li>
  </ul></li>
  <li><a href="#some-notes-and-caveats" id="toc-some-notes-and-caveats" class="nav-link" data-scroll-target="#some-notes-and-caveats">Some Notes and Caveats</a></li>
  <li><a href="#likelihood-in-regression-back-to-our-example" id="toc-likelihood-in-regression-back-to-our-example" class="nav-link" data-scroll-target="#likelihood-in-regression-back-to-our-example">Likelihood in Regression: Back to Our Example</a>
  <ul class="collapse">
  <li><a href="#mathematics-of-likelihood" id="toc-mathematics-of-likelihood" class="nav-link" data-scroll-target="#mathematics-of-likelihood">Mathematics of Likelihood</a></li>
  <li><a href="#log-likelihood" id="toc-log-likelihood" class="nav-link" data-scroll-target="#log-likelihood">Log-Likelihood</a>
  <ul class="collapse">
  <li><a href="#mathematics-of-log-likelihood" id="toc-mathematics-of-log-likelihood" class="nav-link" data-scroll-target="#mathematics-of-log-likelihood">Mathematics of Log-Likelihood</a></li>
  </ul></li>
  <li><a href="#shortcut-the-loglik-function" id="toc-shortcut-the-loglik-function" class="nav-link" data-scroll-target="#shortcut-the-loglik-function">Shortcut: The <code>logLik()</code> Function</a></li>
  <li><a href="#model-complexity" id="toc-model-complexity" class="nav-link" data-scroll-target="#model-complexity">Model Complexity</a></li>
  </ul></li>
  <li><a href="#likelihood-ratio-test-for-nested-models" id="toc-likelihood-ratio-test-for-nested-models" class="nav-link" data-scroll-target="#likelihood-ratio-test-for-nested-models">Likelihood Ratio Test for Nested Models</a>
  <ul class="collapse">
  <li><a href="#hypothesis-test-of-the-lrt" id="toc-hypothesis-test-of-the-lrt" class="nav-link" data-scroll-target="#hypothesis-test-of-the-lrt">Hypothesis Test of the LRT</a></li>
  </ul></li>
  <li><a href="#deviance-a-measure-of-the-modeldata-error" id="toc-deviance-a-measure-of-the-modeldata-error" class="nav-link" data-scroll-target="#deviance-a-measure-of-the-modeldata-error">Deviance: A Measure of the Model–Data Error</a>
  <ul class="collapse">
  <li><a href="#mathematics-of-deviance" id="toc-mathematics-of-deviance" class="nav-link" data-scroll-target="#mathematics-of-deviance">Mathematics of Deviance</a></li>
  <li><a href="#modeling-the-variation-in-the-test-statistic" id="toc-modeling-the-variation-in-the-test-statistic" class="nav-link" data-scroll-target="#modeling-the-variation-in-the-test-statistic">Modeling the Variation in the Test Statistic</a></li>
  </ul></li>
  <li><a href="#using-the-lrtest-function" id="toc-using-the-lrtest-function" class="nav-link" data-scroll-target="#using-the-lrtest-function">Using the <code>lrtest()</code> Function</a></li>
  <li><a href="#evaluating-the-effect-of-news-exposure-in-research-question-2" id="toc-evaluating-the-effect-of-news-exposure-in-research-question-2" class="nav-link" data-scroll-target="#evaluating-the-effect-of-news-exposure-in-research-question-2">Evaluating the Effect of News Exposure in Research Question 2</a></li>
  <li><a href="#evaluating-the-interaction-effect-in-research-question-3" id="toc-evaluating-the-interaction-effect-in-research-question-3" class="nav-link" data-scroll-target="#evaluating-the-interaction-effect-in-research-question-3">Evaluating the Interaction Effect in Research Question 3</a></li>
  <li><a href="#evaluating-assumptions" id="toc-evaluating-assumptions" class="nav-link" data-scroll-target="#evaluating-assumptions">Evaluating Assumptions</a></li>
  <li><a href="#presenting-the-results-from-the-lrts" id="toc-presenting-the-results-from-the-lrts" class="nav-link" data-scroll-target="#presenting-the-results-from-the-lrts">Presenting the Results from the LRTs</a></li>
  <li><a href="#reporting-individual-predictors-from-a-model" id="toc-reporting-individual-predictors-from-a-model" class="nav-link" data-scroll-target="#reporting-individual-predictors-from-a-model">Reporting Individual Predictors From a Model</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Likelihood: A Framework for Evidence</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 12, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="preparation" class="level1">
<h1>Preparation</h1>
<p>In this set of notes, you will learn about the law of likelihood, and the use of likelihood ratios as statistical evidence for model selection. To do so, we will use the <a href="https://raw.githubusercontent.com/zief0002/fluffy-ants/main/data/pew.csv">pew.csv</a> dataset (see the <a href="http://zief0002.github.io/fluffy-ants/codebooks/pew.html">data codebook</a>) to fit a set of models that explain variation in American’s political knowledge.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(educate)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pew <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">"https://raw.githubusercontent.com/zief0002/fluffy-ants/main/data/pew.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>pew</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["id"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["knowledge"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["news"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["age"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["education"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["male"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["ideology"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["party"],"name":[8],"type":["chr"],"align":["left"]},{"label":["engagement"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"10","3":"60","4":"31.1","5":"16","6":"0","7":"65.1","8":"Democrat","9":"19.8"},{"1":"2","2":"18","3":"20","4":"44.4","5":"12","6":"1","7":"41.0","8":"Independent","9":"71.4"},{"1":"3","2":"88","3":"59","4":"53.7","5":"16","6":"1","7":"3.4","8":"Democrat","9":"97.2"},{"1":"4","2":"75","3":"89","4":"62.5","5":"13","6":"1","7":"50.6","8":"Independent","9":"61.5"},{"1":"5","2":"93","3":"43","4":"48.3","5":"16","6":"0","7":"35.3","8":"Democrat","9":"53.4"},{"1":"6","2":"13","3":"61","4":"24.3","5":"9","6":"0","7":"0.1","8":"Independent","9":"41.1"},{"1":"7","2":"37","3":"45","4":"59.2","5":"12","6":"0","7":"13.7","8":"Independent","9":"96.3"},{"1":"8","2":"66","3":"59","4":"93.9","5":"16","6":"1","7":"27.1","8":"Democrat","9":"86.8"},{"1":"9","2":"49","3":"68","4":"37.0","5":"16","6":"0","7":"67.4","8":"Independent","9":"58.2"},{"1":"10","2":"50","3":"44","4":"37.1","5":"14","6":"1","7":"54.8","8":"Democrat","9":"45.2"},{"1":"11","2":"57","3":"92","4":"18.6","5":"18","6":"0","7":"75.7","8":"Republican","9":"83.2"},{"1":"12","2":"65","3":"38","4":"75.0","5":"14","6":"1","7":"46.2","8":"Independent","9":"91.7"},{"1":"13","2":"32","3":"56","4":"47.3","5":"14","6":"1","7":"65.1","8":"Independent","9":"67.3"},{"1":"14","2":"61","3":"69","4":"65.2","5":"16","6":"0","7":"43.4","8":"Republican","9":"53.9"},{"1":"15","2":"58","3":"85","4":"49.9","5":"15","6":"1","7":"29.9","8":"Independent","9":"85.5"},{"1":"16","2":"45","3":"32","4":"25.7","5":"15","6":"0","7":"48.9","8":"Independent","9":"47.1"},{"1":"17","2":"58","3":"69","4":"18.5","5":"12","6":"0","7":"37.8","8":"Republican","9":"55.7"},{"1":"18","2":"49","3":"36","4":"43.0","5":"16","6":"1","7":"57.3","8":"Republican","9":"37.2"},{"1":"19","2":"54","3":"6","4":"24.4","5":"16","6":"1","7":"46.4","8":"Independent","9":"73.6"},{"1":"20","2":"84","3":"79","4":"53.2","5":"13","6":"1","7":"33.9","8":"Independent","9":"76.6"},{"1":"21","2":"92","3":"71","4":"34.2","5":"18","6":"1","7":"48.1","8":"Republican","9":"84.5"},{"1":"22","2":"80","3":"71","4":"52.5","5":"16","6":"0","7":"41.6","8":"Democrat","9":"79.6"},{"1":"23","2":"74","3":"73","4":"49.8","5":"9","6":"0","7":"30.5","8":"Republican","9":"88.9"},{"1":"24","2":"37","3":"71","4":"35.0","5":"15","6":"1","7":"59.2","8":"Republican","9":"37.8"},{"1":"25","2":"49","3":"40","4":"42.1","5":"17","6":"1","7":"48.4","8":"Republican","9":"79.9"},{"1":"26","2":"49","3":"45","4":"33.6","5":"16","6":"0","7":"42.1","8":"Republican","9":"76.0"},{"1":"27","2":"39","3":"37","4":"73.9","5":"15","6":"1","7":"47.9","8":"Democrat","9":"78.2"},{"1":"28","2":"27","3":"60","4":"89.3","5":"8","6":"0","7":"60.0","8":"Independent","9":"75.4"},{"1":"29","2":"50","3":"35","4":"60.8","5":"12","6":"0","7":"44.9","8":"Republican","9":"79.8"},{"1":"30","2":"96","3":"34","4":"58.1","5":"17","6":"1","7":"77.6","8":"Republican","9":"91.0"},{"1":"31","2":"53","3":"68","4":"52.3","5":"15","6":"1","7":"36.0","8":"Democrat","9":"62.9"},{"1":"32","2":"48","3":"20","4":"41.3","5":"16","6":"0","7":"72.0","8":"Republican","9":"86.2"},{"1":"33","2":"45","3":"54","4":"52.6","5":"8","6":"0","7":"53.0","8":"Republican","9":"91.8"},{"1":"34","2":"39","3":"32","4":"43.8","5":"16","6":"0","7":"22.3","8":"Republican","9":"59.0"},{"1":"35","2":"22","3":"14","4":"37.3","5":"10","6":"1","7":"20.9","8":"Independent","9":"72.9"},{"1":"36","2":"31","3":"14","4":"61.7","5":"10","6":"1","7":"62.6","8":"Republican","9":"83.2"},{"1":"37","2":"62","3":"85","4":"31.9","5":"16","6":"1","7":"30.5","8":"Democrat","9":"81.8"},{"1":"38","2":"62","3":"62","4":"57.7","5":"16","6":"0","7":"31.0","8":"Democrat","9":"85.0"},{"1":"39","2":"54","3":"39","4":"36.3","5":"12","6":"1","7":"2.0","8":"Independent","9":"76.0"},{"1":"40","2":"9","3":"32","4":"50.2","5":"12","6":"0","7":"54.0","8":"Independent","9":"7.5"},{"1":"41","2":"67","3":"83","4":"31.0","5":"12","6":"1","7":"29.1","8":"Democrat","9":"77.3"},{"1":"42","2":"79","3":"95","4":"69.3","5":"12","6":"1","7":"38.6","8":"Democrat","9":"61.3"},{"1":"43","2":"57","3":"40","4":"49.6","5":"16","6":"0","7":"6.0","8":"Independent","9":"62.8"},{"1":"44","2":"62","3":"58","4":"67.0","5":"16","6":"1","7":"48.4","8":"Democrat","9":"98.3"},{"1":"45","2":"44","3":"41","4":"65.5","5":"16","6":"1","7":"25.0","8":"Independent","9":"66.1"},{"1":"46","2":"36","3":"65","4":"77.0","5":"13","6":"0","7":"38.8","8":"Independent","9":"58.3"},{"1":"47","2":"66","3":"77","4":"51.6","5":"16","6":"0","7":"57.5","8":"Republican","9":"97.0"},{"1":"48","2":"67","3":"54","4":"42.5","5":"17","6":"0","7":"71.0","8":"Republican","9":"81.6"},{"1":"49","2":"96","3":"94","4":"29.6","5":"16","6":"1","7":"55.1","8":"Republican","9":"77.1"},{"1":"50","2":"27","3":"34","4":"26.9","5":"12","6":"1","7":"52.7","8":"Independent","9":"39.1"},{"1":"51","2":"62","3":"16","4":"53.0","5":"15","6":"1","7":"39.8","8":"Democrat","9":"85.9"},{"1":"52","2":"84","3":"43","4":"51.7","5":"18","6":"0","7":"74.2","8":"Republican","9":"70.2"},{"1":"53","2":"40","3":"6","4":"32.5","5":"18","6":"0","7":"46.7","8":"Democrat","9":"89.4"},{"1":"54","2":"44","3":"35","4":"24.6","5":"12","6":"1","7":"66.0","8":"Republican","9":"52.2"},{"1":"55","2":"75","3":"66","4":"64.4","5":"13","6":"1","7":"27.1","8":"Democrat","9":"95.2"},{"1":"56","2":"52","3":"49","4":"52.3","5":"18","6":"0","7":"49.0","8":"Republican","9":"84.6"},{"1":"57","2":"98","3":"80","4":"56.3","5":"16","6":"1","7":"25.1","8":"Democrat","9":"85.0"},{"1":"58","2":"18","3":"27","4":"72.3","5":"10","6":"0","7":"39.9","8":"Independent","9":"24.3"},{"1":"59","2":"62","3":"53","4":"48.8","5":"15","6":"0","7":"43.5","8":"Republican","9":"80.3"},{"1":"60","2":"41","3":"48","4":"18.0","5":"10","6":"1","7":"54.2","8":"Democrat","9":"46.4"},{"1":"61","2":"67","3":"78","4":"52.1","5":"14","6":"0","7":"66.9","8":"Republican","9":"85.9"},{"1":"62","2":"67","3":"52","4":"43.9","5":"16","6":"1","7":"27.9","8":"Independent","9":"75.7"},{"1":"63","2":"66","3":"38","4":"66.3","5":"13","6":"1","7":"57.7","8":"Republican","9":"68.2"},{"1":"64","2":"62","3":"73","4":"57.5","5":"13","6":"0","7":"54.5","8":"Republican","9":"95.1"},{"1":"65","2":"75","3":"75","4":"69.9","5":"15","6":"0","7":"59.6","8":"Republican","9":"97.1"},{"1":"66","2":"39","3":"46","4":"54.6","5":"12","6":"0","7":"62.8","8":"Independent","9":"67.7"},{"1":"67","2":"41","3":"48","4":"42.9","5":"12","6":"0","7":"47.8","8":"Independent","9":"67.3"},{"1":"68","2":"79","3":"69","4":"35.8","5":"16","6":"1","7":"24.3","8":"Democrat","9":"66.4"},{"1":"69","2":"79","3":"16","4":"28.4","5":"17","6":"0","7":"66.2","8":"Republican","9":"93.1"},{"1":"70","2":"36","3":"89","4":"80.5","5":"16","6":"0","7":"26.5","8":"Democrat","9":"78.6"},{"1":"71","2":"45","3":"29","4":"45.5","5":"12","6":"1","7":"24.4","8":"Democrat","9":"55.5"},{"1":"72","2":"84","3":"77","4":"40.6","5":"16","6":"1","7":"40.1","8":"Democrat","9":"73.0"},{"1":"73","2":"53","3":"71","4":"47.0","5":"12","6":"1","7":"53.9","8":"Republican","9":"64.5"},{"1":"74","2":"76","3":"31","4":"79.1","5":"16","6":"1","7":"58.5","8":"Republican","9":"75.9"},{"1":"75","2":"84","3":"27","4":"45.4","5":"14","6":"0","7":"64.9","8":"Republican","9":"88.1"},{"1":"76","2":"44","3":"97","4":"37.0","5":"15","6":"0","7":"61.7","8":"Democrat","9":"94.3"},{"1":"77","2":"84","3":"54","4":"78.9","5":"16","6":"1","7":"29.8","8":"Independent","9":"67.2"},{"1":"78","2":"58","3":"42","4":"62.5","5":"14","6":"0","7":"23.8","8":"Democrat","9":"84.7"},{"1":"79","2":"92","3":"78","4":"54.2","5":"18","6":"1","7":"49.1","8":"Republican","9":"95.5"},{"1":"80","2":"78","3":"56","4":"66.8","5":"12","6":"1","7":"14.3","8":"Democrat","9":"67.2"},{"1":"81","2":"96","3":"36","4":"62.4","5":"16","6":"1","7":"59.0","8":"Republican","9":"79.4"},{"1":"82","2":"15","3":"57","4":"55.6","5":"12","6":"0","7":"42.0","8":"Republican","9":"71.1"},{"1":"83","2":"41","3":"59","4":"62.6","5":"12","6":"0","7":"27.4","8":"Independent","9":"95.8"},{"1":"84","2":"65","3":"53","4":"70.1","5":"17","6":"1","7":"67.8","8":"Republican","9":"76.9"},{"1":"85","2":"88","3":"50","4":"62.5","5":"16","6":"0","7":"90.0","8":"Independent","9":"84.0"},{"1":"86","2":"52","3":"53","4":"45.9","5":"13","6":"0","7":"82.4","8":"Independent","9":"53.4"},{"1":"87","2":"57","3":"71","4":"42.5","5":"12","6":"1","7":"53.0","8":"Republican","9":"85.7"},{"1":"88","2":"22","3":"19","4":"35.3","5":"12","6":"0","7":"42.4","8":"Independent","9":"59.3"},{"1":"89","2":"49","3":"14","4":"50.4","5":"12","6":"1","7":"53.8","8":"Republican","9":"51.7"},{"1":"90","2":"58","3":"15","4":"49.7","5":"13","6":"1","7":"59.6","8":"Democrat","9":"86.8"},{"1":"91","2":"28","3":"29","4":"56.0","5":"12","6":"1","7":"75.4","8":"Democrat","9":"85.6"},{"1":"92","2":"92","3":"95","4":"73.9","5":"16","6":"1","7":"92.8","8":"Republican","9":"96.3"},{"1":"93","2":"52","3":"92","4":"39.3","5":"17","6":"0","7":"68.4","8":"Republican","9":"87.5"},{"1":"94","2":"58","3":"79","4":"60.3","5":"12","6":"0","7":"57.3","8":"Republican","9":"87.6"},{"1":"95","2":"74","3":"58","4":"34.1","5":"15","6":"1","7":"77.0","8":"Republican","9":"84.5"},{"1":"96","2":"70","3":"71","4":"71.9","5":"16","6":"1","7":"71.0","8":"Republican","9":"77.3"},{"1":"97","2":"70","3":"62","4":"52.8","5":"13","6":"1","7":"53.5","8":"Republican","9":"76.9"},{"1":"98","2":"57","3":"60","4":"76.4","5":"18","6":"0","7":"76.9","8":"Republican","9":"83.9"},{"1":"99","2":"39","3":"40","4":"33.5","5":"12","6":"0","7":"3.8","8":"Democrat","9":"57.6"},{"1":"100","2":"62","3":"37","4":"80.5","5":"11","6":"0","7":"7.1","8":"Democrat","9":"73.3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="research-questions-and-modeling-strategy" class="level1">
<h1>Research Questions and Modeling Strategy</h1>
<p>Recall that we had three research questions for these data:</p>
<ol type="1">
<li>Is there an effect of news exposure on political knowledge?</li>
<li>Is there an effect of news exposure on political knowledge after controlling for demographic and political covariates?</li>
<li>Does education level <em>moderate</em> the effect of news exposure on political knowledge after controlling for demographic and political covariates?</li>
</ol>
<p>Any analysis should begin with looking at plots and computing summary statistics of the sample data. (We already did this in a previous set of notes.) After the data exploration, we can begin to think about fitting one or more models to the data. It is good science to consider the modeling strategy you will be using before you begin fitting models. There are many modeling strategies that educational scientists use in practice (e.g., forward-selection, backward-elimination) and there is no one “right” method. As you consider a modeling strategy, think about how this strategy helps provide a narrative structure for answering your research question; sometimes this leads to one strategy being more productive than others.</p>
<p>In the previous set of notes we began by fitting a model that only included the main-effect of news exposure. Evaluating the effect of news exposure in this model helped us answer RQ 1. We then fitted a model that included news exposure along with the set of demographic and political covariates. Evaluating the effect of news exposure in this model helped us answer RQ 2. Finally, we fitted a model that included an interaction effect of news exposure and education in along with the demographic and political covariates. Evaluating the interaction effect allowed us to answer RQ 3. These three models are:</p>
<p><span class="math display">\[
\begin{split}
\mathbf{Model~1:~} \quad \mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{News~Exposure}_i) + \epsilon_i \\[2ex]
\mathbf{Model~2:~} \quad \mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{Age}_i) + \beta_2(\mathrm{Education}_i) + \beta_3(\mathrm{Male}_i) + \beta_4(\mathrm{Engagement}_i) + \beta_5(\mathrm{Ideology}_i)+ \beta_6(\mathrm{Democrat}_i) + \\ &amp;\beta_7(\mathrm{Republican}_i) + \beta_8(\mathrm{News~Exposure}_i) + \epsilon_i \\[2ex]
\mathbf{Model~3:~} \quad \mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{Age}_i) + \beta_2(\mathrm{Education}_i) + \beta_3(\mathrm{Male}_i) + \beta_4(\mathrm{Engagement}_i) + \beta_5(\mathrm{Ideology}_i)+ \beta_6(\mathrm{Democrat}_i) + \\ &amp;\beta_7(\mathrm{Republican}_i) + \beta_8(\mathrm{News~Exposure}_i) + \beta_9(\mathrm{News~Exposure}_i)(\mathrm{Education}_i) + \epsilon_i \\[2ex]
\end{split}
\]</span></p>
<p>where <span class="math inline">\(\epsilon_i \overset{i.i.d.}{\sim}\mathcal{N}(0,\sigma^2_{\epsilon})\)</span> for each of the models.</p>
<p><br></p>
</section>
<section id="classical-framework-of-evidence" class="level1">
<h1>Classical Framework of Evidence</h1>
<p>When we have looked at statistical evidence to this point, it has been from a hypothesis testing point of view. The primary piece of evidence we use in this paradigm is the <em>p</em>-value. For example, if we fit Model 1 and examine the evidence for the effect of news exposure on news knoledge, we find:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Model 1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.1</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> news, <span class="at">data =</span> pew)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient-level output</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"39.6845434","3":"5.20203862","4":"7.628652","5":"1.558760e-11"},{"1":"news","2":"0.3271158","3":"0.08994213","4":"3.636958","5":"4.421004e-04"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The <em>p</em>-value associated with the effect of news exposure (<span class="math inline">\(p&lt;.001\)</span>), which suggests that the size of this effect is more than we would expect because of chance if the population effect was 0.</p>
<p>Interpreting this <em>p</em>-values, we would say that the probability of seeing the empirical evidence we observed (or evidence that is more extreme) if the null hypothesis that there is no effect of news exposure on news knowledge is true, is 0.000442. This implies that our observed data are inconsistent with the hypothesized model that there is no effect of news exposure. In an applied setting, we might use such evidence to decide that the level of news exposure does indeed predict variation in American’s news knowledge.</p>
<p>Despite being the predominant evidential paradigm used in the education and social sciences, hypothesis testing has many criticisms <span class="citation" data-cites="Johansson:2011 Weakliem:2016">(e.g., <a href="#ref-Johansson:2011" role="doc-biblioref">Johansson, 2011</a>; <a href="#ref-Weakliem:2016" role="doc-biblioref">Weakliem, 2016</a>)</span>. Among some of the stronger criticisms,</p>
<ul>
<li>The <em>p</em>-value only measures evidence against the hypothesized model; not the evidence FOR a particular model.</li>
<li>The model we specify in the null hypothesis is often substantively untenable (how often is the effect 0? Generally as applied scientists the reason we include predictors is because we believe there is an effect.)</li>
<li>The <em>p</em>-value is based on data we haven’t observed (it is based on the observed data AND evidence that is more extreme).</li>
</ul>
<p>If we write the <em>p</em>-value as a probability statement, it would be:</p>
<p><span class="math display">\[
p\mbox{-}\mathrm{value} = P(\mathrm{Data~or~more~extreme~unobserved~data} \mid \mathrm{Model})
\]</span></p>
<p>While hypothesis tests have filled a need in the educational and social science to have some standard for evaluating statistical evidence, it is unclear whether this is the approach we should be using. As statistician David Lindley so aptly states, “[significance tests] are widely used, yet are logically indefensible” <span class="citation" data-cites="Johnstone:1986">(comment in <a href="#ref-Johnstone:1986" role="doc-biblioref">Johnstone, 1986, p. 502</a>)</span>. Psychologist Jacob Cohen was more pointed, saying “[hypothesis testing] has not only failed to support the advance of psychology as a science but also has seriously impeded it” <span class="citation" data-cites="Cohen:1994">(<a href="#ref-Cohen:1994" role="doc-biblioref">Cohen, 1994, p. 997</a>)</span>.</p>
<div class="todo">
<p>“The main purpose of a significance test is to inhibit the natural enthusiasm of the investigator” <span class="citation" data-cites="Mosteller:1954">(<a href="#ref-Mosteller:1954" role="doc-biblioref">Mosteller &amp; Bush, 1954, pp. 331–332</a>)</span>.</p>
</div>
<p><br></p>
</section>
<section id="likelihood-paradigm-to-statistical-evidence" class="level1">
<h1>Likelihood Paradigm to Statistical Evidence</h1>
<p>In applied science, we ideally would like to collect some evidence (data) and use that to say something about how likely a particular model (or hypothesis) is based on that evidence. Symbolically we want to know,</p>
<p><span class="math display">\[
P(\mathrm{Model} \mid \mathrm{Observed~data})
\]</span></p>
<p>This probability is known as the <em>likelihood</em> and is very different than the probability given by the <em>p</em>-value. In the likelihood paradigm, the likelihood is the key piece of statistical evidence used to evaluate models. For example if you were comparing Model A and Model B, you could compute the likelihood for each model and compare them. Whichever model has the higher likelihood has more empirical support. This is, in a nutshell what the <em>Law of Likelihood</em> states. What is even more attractive is that another axiom, the <em>Likelihood Principle</em>, tells us that if the goal is to compare the empirical support of competing models, all of the information in the data that can be used to do so, is contained in the ratio of the model likelihoods. That is, we can’t learn more about which model is more supported unless we collect additional data.</p>
<p><br></p>
</section>
<section id="joint-probability-density-a-roadstop-to-computing-likelihood" class="level1">
<h1>Joint Probability Density: A Roadstop to Computing Likelihood</h1>
<p>In the preparation reading, you learned about the probability density of an observation <span class="math inline">\(x_i\)</span>. Now we will extend this idea to the probability density of a set of observations, say <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, AND <span class="math inline">\(x_k\)</span>. The probability density of a set of observations is referred to as the <em>joint probability density</em>, or simply <em>joint density</em>.</p>
<p>If we can make an assumption about INDEPENDENCE, then the joint probability density would be the product of the individual densities:</p>
<p><span class="math display">\[
p(x_1, x_2, x_3, \ldots, x_k) = p(x_1) \times p(x_2) \times p(x_3) \times \ldots \times p(x_k)
\]</span></p>
<p>Say we had three independent observations, <span class="math inline">\(x =\{60, 65, 67\}\)</span>, from a <span class="math inline">\(\sim\mathcal{N}(50,10)\)</span> distribution. The joint density would be:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute joint density</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">60</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">*</span> <span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">65</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">*</span> <span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">67</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000002947448</code></pre>
</div>
</div>
<p>We could also shortcut this computation,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute joint density</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">65</span>, <span class="dv">67</span>), <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000002947448</code></pre>
</div>
</div>
<p>This value is the joint probability density. The joint probability density indicates the probability of observing the data (<span class="math inline">\(x =\{60, 65, 67\}\)</span>) GIVEN (1) they are drawn from a normal distribution and (2) the normal distribution has a mean of 50 and a standard deviation of 10. In other words, the joint probability density is the probability of the data given a model and parameters of the model.</p>
<p>Symbolically,</p>
<p><span class="math display">\[
\mathrm{Joint~Density} = P(\mathrm{Data} \mid \mathrm{Model~and~Parameters})
\]</span></p>
<p><br></p>
</section>
<section id="computing-likelihood" class="level1">
<h1>Computing Likelihood</h1>
<p>Likelihood is the probability of a particular set of parameters GIVEN (1) the data, and (2) the data are generated from a particular model (e.g., normal distribution). Symbolically,</p>
<p><span class="math display">\[
\mathrm{Likelihood} = P(\mathrm{Parameters} \mid \mathrm{Model~and~Data})
\]</span></p>
<p>Symbolically we denote likelihood with a scripted letter “L” (<span class="math inline">\(\mathcal{L}\)</span>). For example, we might ask the question, given the observed data <span class="math inline">\(x = \{30, 20, 24, 27\}\)</span> come from a normal distribution, what is the likelihood (probability) that the mean is 20 and the standard deviation is 4? We might denote this as,</p>
<p><span class="math display">\[
\mathcal{L}(\mu = 20, \sigma = 4 \mid x)
\]</span></p>
<div class="fyi">
<p><strong>FYI</strong></p>
<p>Although we need to specify the model this is typically not included in the symbolic notation; instead it is often a part of the assumptions.</p>
</div>
<p><br></p>
<section id="an-example-of-computing-and-evaluating-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="an-example-of-computing-and-evaluating-likelihood">An Example of Computing and Evaluating Likelihood</h2>
<p>The likelihood allows us to answer probability questions about a set of parameters. For example, what is the likelihood (probability) that the data (<span class="math inline">\(x = \{30, 20, 24, 27\}\)</span>) were generated from a normal distribution with a mean of 20 and standard deviation of 4? To compute the likelihood we compute the joint probability density of the data under that particular set of parameters.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">20</span>, <span class="dv">24</span>, <span class="dv">27</span>), <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd =</span> <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0000005702554</code></pre>
</div>
</div>
<p>What is the likelihood (probability) that the same set of data (<span class="math inline">\(x = \{30, 20, 24, 27\}\)</span>) were generated from a normal distribution with a mean of 25 and standard deviation of 4?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">20</span>, <span class="dv">24</span>, <span class="dv">27</span>), <span class="at">mean =</span> <span class="dv">25</span>, <span class="at">sd =</span> <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00001774012</code></pre>
</div>
</div>
<p>Given the data and the model, there is more empirical support that the parameters are <span class="math inline">\(\mathcal{N}(25,4^2)\)</span> rather than <span class="math inline">\(\mathcal{N}(20, 4^2)\)</span>, because the likelihood is higher for the former set of parameters. We can compute a ratio of the two likelihoods to quantify the amount of additional support for the <span class="math inline">\(\mathcal{N}(25,4^2)\)</span>.</p>
<p><span class="math display">\[
\begin{split}
\mathrm{Likelihood~Ratio} &amp;= \frac{0.00001774012}{0.0000005702554} \\[1ex]
&amp;= 31.11
\end{split}
\]</span></p>
<p>The empirical support for the <span class="math inline">\(\mathcal{N}(25,4^2)\)</span> parameterization is 31 times that of the <span class="math inline">\(\mathcal{N}(20, 4^2)\)</span> parameterization! In a practical setting, this would lead us to adopt a mean of 25 over a mean of 20.</p>
<p><br></p>
</section>
</section>
<section id="some-notes-and-caveats" class="level1">
<h1>Some Notes and Caveats</h1>
<p>It is important to note that although we use the joint probability under a set of parameters to compute the likelihood of those parameters, theoretically joint density and likelihood are very different. Likelihood takes the data and model as given and computes the probability of a set of parameters. Whereas joint density assumes that the model and parameters are given and gives us the probability of the data.</p>
<div class="fyi">
<p><strong>FYI</strong></p>
<p>Likelihood refers to the probability of the parameters and joint probability density refers to the probability of the data.</p>
</div>
<p>Once we collect the data, the probability of observing that set of data is 1; it is no longer unknown. The likelihood method treats our data as known and offers us a way of making probabilistic statements about the unknown parameters. This is more aligned with our scientific process than making some assumption about the parameter (e.g., <span class="math inline">\(\beta_1=0\)</span>) and then trying to determine the probability of the data under that assumption. Moreover, likelihood does not use unobserved data (e.g., data more extreme than what we observed) in the computation.</p>
<p>It is also important to acknowledge what likelihood and the likelihood ratio don’t tell us. First, they only tell us the probability of a set of parameters for the data we have. Future collections of data might change the amount of support or which set of parameters is supported. Since changing the data, changes the likelihood, this also means we cannot make cross study comparisons of the likelihood (unless the studies used the exact same data). Secondly, the model assumed is important. If a different model is assumed, the likelihood will be different, and again could change the amount of support or which set of parameters is supported.</p>
<p>The likelihood ratio (LR), while useful for comparing the relative support between parameterizations, does not tell you that a particular parameterization is correct. For example, the LR of 31.11 tells us that there is more empirical support for the <span class="math inline">\(\mathcal{N}(25,4^2)\)</span> parameterization than <span class="math inline">\(\mathcal{N}(20, 4^2)\)</span>. But, there might be even more support for a parameterization we haven’t considered.</p>
<p>These shortcomings are not unique to the likelihood paradigm The also exist in the classical hypothesis testing paradigm for statistical evidence. All in all, the added advantages to the likelihood paradigm make it more useful to applied work than hypothesis testing.</p>
<p><br></p>
</section>
<section id="likelihood-in-regression-back-to-our-example" class="level1">
<h1>Likelihood in Regression: Back to Our Example</h1>
<p>When fitting a regression model, we make certain assumptions about the relationship between a set of predictors and the outcome. For example, in Model 1 from our earlier example, we assume that the relationship between news exposure and news knowledge can be described by the following model:</p>
<p><span class="math display">\[
\begin{split}
\mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{News~Exposure}_i) + \epsilon_i \\[1ex]
&amp;\mathrm{where~}\epsilon_i \overset{i.i.d.}{\sim}\mathcal{N}(0,\sigma^2_{\epsilon})
\end{split}
\]</span></p>
<p>Here we use OLS to estimate the regression coefficients. Then we can use those, along with the observed data to obtain the residuals and the estimate for the residual standard error. The residuals are the GIVEN data and the set up distributional assumptions for the model (e.g., normal, mean of 0, constant variance) allow us to compute the likelihood for the entire set of parameters in this model (<span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\sigma^2_{\epsilon}\)</span>).</p>
<p>Below is a set of syntax to compute the likelihood, based on fitting <code>lm.1</code>. We use the <code>resid()</code> function to compute the residuals. (It is the same as grabbing the column called <code>.resid</code> from the <code>augment()</code> output.) We also use the estimated value of the residual standard error (<span class="math inline">\(\hat{\sigma}_{\epsilon} = 20.3\)</span>) from the <code>glance()</code> output.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get RSE for use in likelihood</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["r.squared"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["adj.r.squared"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sigma"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["df"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["logLik"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["deviance"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["df.residual"],"name":[11],"type":["int"],"align":["right"]},{"label":["nobs"],"name":[12],"type":["int"],"align":["right"]}],"data":[{"1":"0.1189226","2":"0.1099321","3":"20.26189","4":"13.22746","5":"0.0004421004","6":"1","7":"-441.7579","8":"889.5158","9":"897.3313","10":"40233.33","11":"98","12":"100"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute likelihood for lm.1</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">resid</span>(lm<span class="fl">.1</span>), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">20.3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.382925e-192</code></pre>
</div>
</div>
<p>This value by itself is somewhat meaningless. It is only worthwhile when we compare it to the likelihood from another model. For example, let’s compute the likelihood for an intercept-only model (Model 0) and compare this to the likelihood for <code>lm.1</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Model 0</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.0</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> pew)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get RSE for use in likelihood</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm<span class="fl">.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["r.squared"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["adj.r.squared"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["sigma"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["df"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["logLik"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["BIC"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["deviance"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["df.residual"],"name":[11],"type":["int"],"align":["right"]},{"label":["nobs"],"name":[12],"type":["int"],"align":["right"]}],"data":[{"1":"0","2":"0","3":"21.47674","4":"NA","5":"NA","6":"NA","7":"-448.0884","8":"900.1768","9":"905.3871","10":"45663.79","11":"99","12":"100"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute likelihood for lm.2</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">resid</span>(lm<span class="fl">.0</span>), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">21.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.489266e-195</code></pre>
</div>
</div>
<p>The likelihood value for <code>lm.1</code> is higher than the likelihood value for <code>lm.0</code>. Computing the likelihood ratio:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">1.382925e-192</span> <span class="sc">/</span> <span class="fl">2.489266e-195</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 555.5553</code></pre>
</div>
</div>
<p>This suggests that given the data, Model 1 is 555.6 times more likely than Model 0. In practice, we would adopt Model 1 over Model 0 because it is more likely given the empirical evidence (data) we have.</p>
<section id="mathematics-of-likelihood" class="level3 mathnote">
<h3 class="anchored" data-anchor-id="mathematics-of-likelihood">Mathematics of Likelihood</h3>
<p>Being able to express the likelihood mathematically is important for quantitative methodologists as it allows us to manipulate and study the likelihood function and its properties. It also gives us insight into how the individual components of the likelihood affect its value.</p>
<p>Remember, we can express the likelihood of the regression residuals mathematically as:</p>
<p><span class="math display">\[
\mathcal{L}(\beta_0, \beta_1 | \mathrm{data}) = p(\epsilon_1) \times p(\epsilon_2) \times \ldots \times p(\epsilon_n)
\]</span></p>
<p>where the probability density of each residual (assuming normality) is:</p>
<p><span class="math display">\[
p(\epsilon_i) = \frac{1}{\sigma\sqrt{2\pi}}\exp\left[-\frac{(\epsilon_i-\mu)^2}{2\sigma^2}\right]
\]</span></p>
<p>In addition to normality, which gives us the equation to compute the PDF for each residual, the regression assumptions also specify that each conditional error distribution has a mean of 0 and some variance (that is the same for all conditional error distributions). We can call it <span class="math inline">\(\sigma^2_{\epsilon}\)</span>. Substituting these values into the density function, we get,</p>
<p><span class="math display">\[
\begin{split}
p(\epsilon_i) &amp;= \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}}\exp\left[-\frac{(\epsilon_i-0)^2}{2\sigma^2_{\epsilon}}\right] \\[1em]
&amp;= \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}}\exp\left[-\frac{(\epsilon_i)^2}{2\sigma^2_{\epsilon}}\right]
\end{split}
\]</span></p>
<p>Now we use this expression for each of the <span class="math inline">\(p(\epsilon_i)\)</span> values in the likelihood computation.</p>
<p><span class="math display">\[
\begin{split}
\mathcal{L}(\beta_0, \beta_1 | \mathrm{data}) &amp;= p(\epsilon_1) \times p(\epsilon_2) \times \ldots \times p(\epsilon_n) \\[1em]
&amp;= \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}}\exp\left[-\frac{\epsilon_1
^2}{2\sigma^2_{\epsilon}}\right] \times \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}}\exp\left[-\frac{\epsilon_2^2}{2\sigma^2_{\epsilon}}\right] \times \\
&amp;~~~~~~\ldots \times \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}}\exp\left[-\frac{\epsilon_n^2}{2\sigma^2_{\epsilon}}\right]
\end{split}
\]</span></p>
<p>We can simplify this:</p>
<p><span class="math display">\[
\begin{split}
\mathcal{L}(\beta_0, \beta_1 | \mathrm{data}) &amp;=\left[ \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}} \right]^n \times \exp\left[-\frac{\epsilon_1^2}{2\sigma^2_{\epsilon}}\right] \times \exp\left[-\frac{\epsilon_2^2}{2\sigma^2_{\epsilon}}\right] \times \ldots \\
&amp;~~~~~~ \times \exp\left[-\frac{\epsilon_n^2}{2\sigma^2_{\epsilon}}\right]
\end{split}
\]</span> We can also simplify this by using the product notation:</p>
<p><span class="math display">\[
\mathcal{L}(\beta_0, \beta_1 | \mathrm{data}) =\left[ \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}} \right]^n \times \prod_{i=1}^n \exp\left[-\frac{\epsilon_i^2}{2\sigma^2_{\epsilon}}\right]
\]</span> We can also write the residuals (<span class="math inline">\(\epsilon_i\)</span>) as a function of the regression parameters we are trying to find the likelihood for.</p>
<p><span class="math display">\[
\mathcal{L}(\beta_0, \beta_1 | \mathrm{data}) =\left[ \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}} \right]^n \times \prod_{i=1}^n \exp\left[-\frac{\big[Y_i - \beta_0 - \beta_1(X_i)\big]^2}{2\sigma^2_{\epsilon}}\right]
\]</span></p>
<p>where <span class="math inline">\(\sigma^2_{\epsilon} = \frac{\sum \epsilon_i^2}{n}\)</span>. Because the numerator of <span class="math inline">\(\sigma^2_{\epsilon}\)</span> can be written as <span class="math inline">\(\sum_i^n\big(Y_i - \beta_0 - \beta_1(X_i)\big)^2\)</span>, we see that the likelihood is a function of <span class="math inline">\(n\)</span>, and the regression coefficients, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Moreover, <span class="math inline">\(n\)</span> is based on the data (which is given) and is thus is a constant. Mathematically, this implies that the only variables (values that can vary) in the likelihood function are the regression coefficients.</p>
</section>
<p><br></p>
<section id="log-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="log-likelihood">Log-Likelihood</h2>
<p>The likelihood values are quite small since we are multiplying several probability densities (values between 0 and 1) together. Since it is hard to work with these smaller values, in practice, we often compute and work with the natural logarithm of the likelihood. So in our example, Model 0 (<span class="math inline">\(\mathcal{L}_0 = 2.489266 \times 10^{-195}\)</span>) has a log-likelihood of:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood for Model 0</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fl">2.489266e-195</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -448.0921</code></pre>
</div>
</div>
<p>Similarly, we can compute the log-likelihood for Model 1 as:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood for Model 1</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fl">1.382925e-192</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -441.7721</code></pre>
</div>
</div>
<p>We typically denote log-likelihood using a scripted lower-case “l” (<span class="math inline">\(\mathcal{l}\)</span>). Here,</p>
<p><span class="math display">\[
\begin{split}
\mathcal{l}_0 &amp;= -448.0921 \\[1ex]
\mathcal{l}_1 &amp;= -441.7721 \\[1ex]
\end{split}
\]</span></p>
<p>Note that the logarithm of a decimal will be negative, so the log-likelihood will be a negative value. Less negative log-likelihood values correspond to higher likelihood values, which indicate more empirical support. Here Model 1 has a log-likelihood value (<span class="math inline">\(-441.8\)</span>) that is less negative than Model 0’s log-likelihood value (<span class="math inline">\(-448.1\)</span>), which indicates there is more empirical support for Model 1 than Model 0.</p>
<div class="fyi">
<p><strong>FYI</strong></p>
<p>While it is possible using algebra to express the likelihood ratio using log-likelihoods, it does not have the same interpretational value as the LR does. Because of this, the likelihood ratio is not often expresseds using log-likelihoods.</p>
</div>
<!-- We can also express the likelihood ratio using log-likelihoods. To do so we take the natural logarithm of the likelihood ratio. We also re-write it using the rules of logarithms (from algebra). -->
<!-- $$ -->
<!-- \begin{split} -->
<!-- \ln(\mathrm{LR}) &= \ln \bigg(\frac{\mathcal{L}_2}{\mathcal{L}_1}\bigg) \\[2ex] -->
<!-- &= \ln \big(\mathcal{L}_2\big) - \ln \big(\mathcal{L}_1\big) -->
<!-- \end{split} -->
<!-- $$ -->
<!-- That is, we can find an equivalent relative support metric to the LR based on the log-likelihoods by computing the difference between them. For our example: -->
<!-- ```{r} -->
<!-- # Difference in log-likelihoods -->
<!-- log(2.910762e-196) - log(2.089334e-199) -->
<!-- # Equivalent to ln(LR) -->
<!-- log(2.910762e-196 / 2.089334e-199) -->
<!-- ``` -->
<!-- Unfortunately, this difference doesn't have the same interpretational value as the LR does, bcause this difference is in log-units. In order to get that interpretation back, we need to exponentiate (the reverse function of the logarithm) the difference: -->
<!-- ```{r} -->
<!-- # Exponentiate the difference in log-likelihoods -->
<!-- exp(7.239325) -->
<!-- ``` -->
<!-- Again, Model 1 has 308244.9 times the empirical support than Model 0. -->
<section id="mathematics-of-log-likelihood" class="level3 mathnote">
<h3 class="anchored" data-anchor-id="mathematics-of-log-likelihood">Mathematics of Log-Likelihood</h3>
<p>We can express the log-likelihood of the regression residuals mathematically by taking the natural logarithm of the likelihood we computed earlier:</p>
<p><span class="math display">\[
\begin{split}
\ln \Bigl(\mathcal{L}(\beta_0, \beta_1 | \mathrm{data})\Bigr) &amp;= \ln \Biggl( \left[ \frac{1}{\sigma_{\epsilon}\sqrt{2\pi}} \right]^n \times \exp\left[-\frac{\epsilon_1^2}{2\sigma^2_{\epsilon}}\right] \times  \\
&amp;~~~~~~ \exp\left[-\frac{\epsilon_2^2}{2\sigma^2_{\epsilon}}\right] \times \ldots \times \exp\left[-\frac{\epsilon_n^2}{2\sigma^2_{\epsilon}}\right] \Biggr) \\
\end{split}
\]</span></p>
<p>Using our rules for logarithms and re-arranging gives,</p>
<p><span class="math display">\[
\mathcal{l}(\beta_0, \beta_1 | \mathrm{data}) = -\frac{n}{2} \times \ln (2\pi\sigma^2_{\epsilon}) - \frac{1}{2\sigma^2_{\epsilon}} \times \sum \epsilon_i^2
\]</span></p>
<p>Examining this equation, we see that the log-likelihood is a function of <span class="math inline">\(n\)</span>, <span class="math inline">\(\sigma^2_{\epsilon}\)</span> and the sum of squared residuals (SSR)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. We can of course, re-express this using the the regression parameters:</p>
<p><span class="math display">\[
\mathcal{l}(\beta_0, \beta_1 | \mathrm{data}) = -\frac{n}{2} \times \ln (2\pi\sigma^2_{\epsilon}) - \frac{1}{2\sigma^2_{\epsilon}} \times \sum \big[Y_i - \beta_0 - \beta_1(X_i)\big]^2
\]</span></p>
<p>And, again, since <span class="math inline">\(\sigma^2_{\epsilon}\)</span> is a function of the regression coefficients and <span class="math inline">\(n\)</span>, this means that the only variables in the log-likelihood function are the coefficients.</p>
</section>
<p><br></p>
</section>
<section id="shortcut-the-loglik-function" class="level2">
<h2 class="anchored" data-anchor-id="shortcut-the-loglik-function">Shortcut: The <code>logLik()</code> Function</h2>
<p>The <code>logLik()</code> function can be used to obtain the log-likelihood directly from a fitted model object. For example, to find the log-likelihood for Model 1, we can use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for Model 1</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(lm<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -441.7579 (df=3)</code></pre>
</div>
</div>
<p>The <code>df</code> output tells us how many <strong>total parameters</strong> are being estimated in the model. In our case the number of total parameters in Model 0 is three (<span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_{\mathrm{News~Exposure}}\)</span>, and <span class="math inline">\(\sigma^2_{\epsilon}\)</span>). What is more important to us currently, is the log-likelihood value; <span class="math inline">\(\mathcal{l}_1=-450.2233\)</span>.</p>
<p>This value is slightly different than the log-likelihood we just computed of <span class="math inline">\(-441.7721\)</span>. This is not because of rounding in this case. It has to do with how the model is being estimated; the <code>logLik()</code> function assumes the parameters are being estimated using maximum likelihood (ML) rather than ordinary least squares (OLS). You can learn more about ML estimation in the optional set of notes, but for now, we will just use <code>logLik()</code> to compute the log-likelihood.</p>
<p>Here we compute the log-likelihood for Model 0 using the <code>logLik()</code> function. We also use the output to compute the likelihood for Model 0. To compute the likelihood from the log-likelihood we need to exponentiate (the reverse function of the logarithm) the the log-likelihood value using the <code>exp()</code> function. We also compute the log-likelihood and likelihood value for Model 1.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for Model 0</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(lm<span class="fl">.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -448.0884 (df=2)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute likelihood for Model 0</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">logLik</span>(lm<span class="fl">.0</span>)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.498531e-195</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for Model 1</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(lm<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -441.7579 (df=3)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute likelihood for Model 1</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">logLik</span>(lm<span class="fl">.1</span>)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.402758e-192</code></pre>
</div>
</div>
<p>Because the output from <code>logLik()</code> includes extraneous information (e.g., <code>df</code>), we use indexing (square brackets) to extract only the part of the output we want. In this case, the <code>[1]</code> extracts the log-likelihood value from the <code>logLik()</code> output (ignoring the <code>df</code> part).</p>
<p><br></p>
</section>
<section id="model-complexity" class="level2">
<h2 class="anchored" data-anchor-id="model-complexity">Model Complexity</h2>
<p>One aspect that we need to consider is that more complex models tend to have higher likelihoods and log-likelihoods. Therefore when we compare likelihoods (or log-likelihoods) we need to consider the complexity in addition to the likelihoods. One way to quantify a model’s complexity is to consider the number of parameters that are being estimated. The more parameters that we need to estimate, the more complex the model. Recall that the number of parameters for a model are given in the <code>df</code> value from the <code>logLik()</code> function’s output.</p>
<p>In our example, the <code>df</code> value for Model 0 is two, indicating that this model is estimating two parameters (<span class="math inline">\(\beta_0\)</span>, and <span class="math inline">\(\sigma^2_{\epsilon}\)</span>). For Model 1, the <code>df</code> value was three. This indicates that Model 1 is more complex than Model 0.</p>
<p>As we consider using the likelihood ratio (LR) or the difference in log-likelihoods for model selection, we also need to consider the model complexity. In our example, the likelihood ratio of 555.6 indicates that Model 1 has approximately 555.6 times the empirical support than Model 0. But, Model 1 is more complex than Model 0, so we would expect that it would be more empirically supported.</p>
<p>In this case, with a likelihood ratio of 555.6, it seems like the empirical data certainly support adopting Model 1 over Model 0. despite the added complexity of Model 1. But what if the LR was 10? Would that be enough additional support to warrant adopting Model 1 over Model 0? What about a LR of 5?</p>
<p><br></p>
</section>
</section>
<section id="likelihood-ratio-test-for-nested-models" class="level1">
<h1>Likelihood Ratio Test for Nested Models</h1>
<p>One key question that arises is, if the likelihood for a more complex model is higher than the likelihood for a simpler model, how large does the likelihood ratio have to be before we adopt the more complex model? In general, there is no perfect answer for this.</p>
<p>If the models being compared are nested, then we can carry out a hypothesis test<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> to see if the LR is more than we would expect because of chance. Models are nested when the parameters in the simpler model are a subset of the parameters in the more complex model. For example, in our example, the parameters in Model 0 are a subset of the parameters in Model 1:</p>
<p><span class="math display">\[
\begin{split}
\mathbf{Model~1~Parameters:}&amp;\quad\{\beta_0,~\beta_{\mathrm{News~Exposure}},~\sigma^2_{\epsilon}\} \\[1ex]
\mathbf{Model~0~Parameters:}&amp;\quad\{\beta_0,~\sigma^2_{\epsilon}\} \\[1ex]
\end{split}
\]</span></p>
<p>The parameters for Model 0 all appear in the list of parameters for Model 1. Because of this we can say that Model 0 is <em>nested</em> in Model 1.</p>
<p><br></p>
<section id="hypothesis-test-of-the-lrt" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-test-of-the-lrt">Hypothesis Test of the LRT</h2>
<p>When we have nested models we can carry out a hypothesis test to decide between the following competing hypotheses:</p>
<p><span class="math display">\[
\begin{split}
H_0:&amp; ~\theta_0 = \{\beta_0,~\sigma^2_{\epsilon}\}\\[1ex]
H_A:&amp; \theta_1 = \{\beta_0,~\beta_{\mathrm{News~Exposure}},~\sigma^2_{\epsilon}\}
\end{split}
\]</span></p>
<p>where <span class="math inline">\(\theta_0\)</span> refers to the simpler model and <span class="math inline">\(\theta_1\)</span> refers to the more complex model. This translates to adopting either the simpler model (fail to reject <span class="math inline">\(H_0\)</span>) or the more complex model (reject <span class="math inline">\(H_0\)</span>). To carry out this test, we translate our likelihood ratio to a test statistic called <span class="math inline">\(\chi^2\)</span> (pronounced chi-squared):</p>
<p><span class="math display">\[
\chi^2 = -2 \ln \bigg(\frac{\mathcal{L}({\theta_0})}{\mathcal{L}({\theta_1})}\bigg)
\]</span></p>
<p>That is we compute <span class="math inline">\(-2\)</span> times the log of the likelihood ratio where the likelihood for the simpler model is in the numerator. (Note this is the inverse of how we have been computing the likelihood ratio!) Equivalently, we can compute this as:</p>
<p><span class="math display">\[
\chi^2 = -2 \bigg(\ln \bigg[\mathcal{L}({\theta_0})\bigg] - \ln \bigg[\mathcal{L}({\theta_1})\bigg]\bigg)
\]</span></p>
<p>For our example, we compute this using the following syntax:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute chi-squared</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(lm<span class="fl">.0</span>)[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">logLik</span>(lm<span class="fl">.1</span>)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.66099</code></pre>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="deviance-a-measure-of-the-modeldata-error" class="level1">
<h1>Deviance: A Measure of the Model–Data Error</h1>
<p>If we re-write the formula for the <span class="math inline">\(\chi^2\)</span>-statistic by distributing the <span class="math inline">\(-2\)</span>, we get a better glimpse of what this statistic is measuring.</p>
<p><span class="math display">\[
\chi^2 = -2 \ln \bigg[\mathcal{L}({\theta_0})\bigg] - \bigg(-2\ln \bigg[\mathcal{L}({\theta_1})\bigg]\bigg)
\]</span></p>
<p>The quantity <span class="math inline">\(-2\ln\big[\mathcal{L}(\theta_k)\big]\)</span> is referred to as the <em>residual deviance</em><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> of Model K. It measures the amount of misfit between the model and the data. (As such, when evaluating deviance values, lower is better.) For linear models, with the classic assumptions (<span class="math inline">\(\overset{i.i.d.}{\sim}\mathcal{N}(0,\sigma^2_{\epsilon})\)</span>), the deviance is a function of the residual sum of squares (RSS):</p>
<p><span class="math display">\[
\mathrm{Deviance} = n \ln\big(2\pi\sigma^2_{\epsilon}\big) + \frac{\mathrm{RSS}}{\sigma^2_{\epsilon}}
\]</span></p>
<p>where <span class="math inline">\(\mathrm{RSS}=\sum\epsilon_i^2\)</span> and <span class="math inline">\(\sigma^2_{\epsilon} = \frac{\mathrm{RSS}}{n}\)</span>. This formula illustrates that the residual deviance is a generalization of the residual sum of squares (RSS), and measures the model–data misfit.</p>
<section id="mathematics-of-deviance" class="level2 mathnote">
<h2 class="anchored" data-anchor-id="mathematics-of-deviance">Mathematics of Deviance</h2>
<p>We can express the deviance mathematically by multiplying the log-likelihood by <span class="math inline">\(-2\)</span>.</p>
<p><span class="math display">\[
\begin{split}
\mathrm{Deviance} &amp;= -2 \times\mathcal{l}(\beta_0, \beta_1 | \mathrm{data}) \\[1ex]
&amp;= -2 \bigg(-\frac{n}{2} \times \ln (2\pi\sigma^2_{\epsilon}) - \frac{1}{2\sigma^2_{\epsilon}} \times \sum \epsilon_i^2\bigg) \\[1ex]
&amp;= -n\ln (2\pi\sigma^2_{\epsilon}) + \frac{1}{\sigma^2_{\epsilon}}\sum \epsilon_i^2 \\[1ex]
&amp;= -n\ln (2\pi\sigma^2_{\epsilon}) + \frac{\mathrm{RSS}}{\sigma^2_{\epsilon}}
\end{split}
\]</span></p>
<p>Rewriting this using the parameters from the likelihood:</p>
<p><span class="math display">\[
\mathrm{Deviance} = -n\ln (2\pi\sigma^2_{\epsilon}) + \frac{\sum_{i=1}^n \big[Y_i-\beta_0-\beta_1(X_i)\big]^2}{\sigma^2_{\epsilon}}
\]</span></p>
<p>Once again, we find that the only variables in the deviance function are the regression coefficients.</p>
</section>
<p>In practice, we will use the <code>logLik()</code> function to compute the deviance.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the deviance for Model 0</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">logLik</span>(lm<span class="fl">.0</span>)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 896.1768</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the deviance for Model 1</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">logLik</span>(lm<span class="fl">.1</span>)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 883.5158</code></pre>
</div>
</div>
<p>Here the deviance for Model 1 (883.5) is less than the deviance for Model 0 (896.2). This indicates that the data have better fit to Model 1 than Model 0. How much better is the model–data fit for Model 1?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute difference in deviances</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fl">896.2</span> <span class="sc">-</span> <span class="fl">883.5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.7</code></pre>
</div>
</div>
<p>Model 1 improves the fit (reduces the misfit) by 12.7 over Model 0. This is the value of our <span class="math inline">\(\chi^2\)</span>-statistic. That is, the <span class="math inline">\(\chi^2\)</span>-statistic is the difference in residual deviance values and measures the amount of improvement in the model–data misfit.</p>
<p><br></p>
<section id="modeling-the-variation-in-the-test-statistic" class="level2">
<h2 class="anchored" data-anchor-id="modeling-the-variation-in-the-test-statistic">Modeling the Variation in the Test Statistic</h2>
<p>If the null hypothesis is true, the difference in deviances can be modeled using a <span class="math inline">\(\chi^2\)</span>-distribution. The degrees-of-freedom for this <span class="math inline">\(\chi^2\)</span>-distribution is based on the difference in the number of parameters between the complex and simpler model. In our case this difference is four (<span class="math inline">\(3-2=1\)</span>):</p>
<p><span class="math display">\[
\chi^2(1) = 12.66
\]</span></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dataset</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>fig_01 <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">X =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">20</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y =</span> <span class="fu">dchisq</span>(<span class="at">x =</span> X, <span class="at">df =</span> <span class="dv">1</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out X&lt;=65</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>shaded <span class="ot">=</span> fig_01 <span class="sc">%&gt;%</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(X <span class="sc">&gt;=</span><span class="fl">12.66</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> fig_01, <span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">y =</span> Y)) <span class="sc">+</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Chi-squared"</span>) <span class="sc">+</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Probability density"</span>) <span class="sc">+</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> shaded, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">10</span>, <span class="fu">aes</span>(<span class="at">ymax =</span> Y), <span class="at">color =</span> <span class="st">"#bbbbbb"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-01" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Plot of the probability density function (PDF) for a $\chi^2(1)$ distribution. The grey shaded area represents the *p*-value based on $\chi^2=12.66$.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-likelihood-evidence_files/figure-html/fig-01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%" alt="Plot of the probability density function (PDF) for a $\chi^2(1)$ distribution. The grey shaded area represents the *p*-value based on $\chi^2=12.66$.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Plot of the probability density function (PDF) for a <span class="math inline">\(\chi^2(1)\)</span> distribution. The grey shaded area represents the <em>p</em>-value based on <span class="math inline">\(\chi^2=12.66\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>To compute the <em>p</em>-value we use the <code>pchisq()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute p-value for X^2(1) = 14.50</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">12.66</span>, <span class="at">df =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003735622</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative method</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">12.66</span>, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003735622</code></pre>
</div>
</div>
<p>Based on the <em>p</em>-value, we would reject the null hypothesis for the likelihood ratio test, which suggests that we should adopt the more complex model (Model 1). This means that the model that includes the effect of news exposure is more empirically supported than a model that includes no predictors. Note that we are making a holistic evaluation about the model rather than about individual predictors.</p>
<!-- To determine how much more variation Model 1 explains in news knowledge than Model 0 does, we look at the $R^2$ values from the `glance()` output. -->
<!-- ```{r} -->
<!-- # Model-level output Model 0 -->
<!-- glance(lm.0) -->
<!-- # Model-level output Model 1 -->
<!-- glance(lm.1) -->
<!-- ``` -->
<!-- Model 1 explains 26.4% of the variation in peer ratings compared to Model 0, which explains 0% of the variation in peer ratings. This difference is statistically significant based on the *p*-value obtained from the likelihood ratio test ($p=0.000041$).  -->
<p><br></p>
</section>
</section>
<section id="using-the-lrtest-function" class="level1">
<h1>Using the <code>lrtest()</code> Function</h1>
<p>In practice, we can also use the <code>lrtest()</code> function from the <code>{lmtest}</code> package to carry out a likelihood ratio test. We provide this function the name of the model object for the simpler model, followed by the name of the model object for the more complex model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># LRT to compare Model 0 and Model 1</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.0</span>, lm<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"-448.0884","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"3","2":"-441.7579","3":"1","4":"12.66099","5":"0.0003733655","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="evaluating-the-effect-of-news-exposure-in-research-question-2" class="level1">
<h1>Evaluating the Effect of News Exposure in Research Question 2</h1>
<p>In RQ 2, we are evaluating the effect of news exposure on news knowledge after controlling for the set of political and demographic covariates. To do this using a likelihood ratio test, we need to compare a baseline model that includes all of the covariates to a model that includes the covariates AND the effect of news exposure. That is, the only thing that is different between the two models is that the second model includes the effect of news exposure on top of the covariates. That is we will be comparing the following two models:</p>
<p><span class="math display">\[
\begin{split}
\mathbf{Simple~Model:~} \quad \mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{Education}_i) + \beta_2(\mathrm{Male}_i) + \beta_3(\mathrm{Engagement}_i) + \epsilon_i \\[2ex]
\mathbf{Complex~Model:~} \quad \mathrm{News~Knowledge}_i = &amp;\beta_0 + \beta_1(\mathrm{Education}_i) + \beta_2(\mathrm{Male}_i) + \beta_3(\mathrm{Engagement}_i) + \beta_8(\mathrm{News~Exposure}_i) + \epsilon_i \\[2ex]
\end{split}
\]</span></p>
<p>By comparing the parameters of the two models, we can see that the simpler model is nested in the more complex model.</p>
<p><span class="math display">\[
\begin{split}
\mathbf{Simple~Model~Parameters:}&amp;\quad\{\beta_0,~\beta_{\mathrm{Education}},~\beta_{\mathrm{Male}},~\beta_{\mathrm{Engagement}},~\sigma^2_{\epsilon}\} \\[1ex]
\mathbf{Complex~Model~Parameters:}&amp;\quad\{\beta_0, ~\beta_{\mathrm{Education}},~\beta_{\mathrm{Male}},~\beta_{\mathrm{Engagement}},~\beta_{\mathrm{News~Exposure}},~\sigma^2_{\epsilon}\} \\[1ex]
\end{split}
\]</span></p>
<p>To carry out the LRT we fit the two models, compute the difference in model deviances, and evaluate that difference in a <span class="math inline">\(\chi^2\)</span>-distribution with degrees-of-freedom equal to the difference in model complexity (based on the number of parameters being estimated).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.2</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement, <span class="at">data =</span> pew)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Complex model</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.3</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news, <span class="at">data =</span> pew)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the difference in deviances between Model 1 and Model 2</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">logLik</span>(lm<span class="fl">.2</span>)[<span class="dv">1</span>] <span class="sc">-</span> (<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">logLik</span>(lm<span class="fl">.3</span>)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.924345</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the difference in model complexity</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="dv">6</span> <span class="sc">-</span> <span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute p-value for X^2(1) = 7.960401</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">8.924345</span>, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002813943</code></pre>
</div>
</div>
<p>The <em>p</em>-value is 0.002813943, suggesting that there is an effect of news exposure on news knowledge, after controlling for the set of political and demographic covariates. Again, we could also obtain this same result via using the <code>lrtest()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LRT to compare Model 2 and Model 3</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.2</span>, lm<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"5","2":"-420.7773","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"6","2":"-416.3151","3":"1","4":"8.924345","5":"0.002813942","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="evaluating-the-interaction-effect-in-research-question-3" class="level1">
<h1>Evaluating the Interaction Effect in Research Question 3</h1>
<p>To evaluate the potential interaction effect between news exposure and education on news knowledge, after controlling for demographic and political covariates, we need to fit the interaction model and then compare it to a model that includes all the same predictors EXCEPT the interaction effect.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit interaction model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that Model 3 (fitted earlier) is the baseline comparison model to evaluate the interaction effect. Here we will use the <code>lrtest()</code> function to compare Models 3 and 4 to evaluate the interaction effect.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LRT to compare Model 1 and Model 2</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.3</span>, lm<span class="fl">.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-416.3151","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"5.150592","5":"0.02323844","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The <em>p</em>-value is 0.02324, suggesting that there is an interaction effect between news exposure and education level after controlling for differences in the set of political and demographic covariates.</p>
<p><br></p>
</section>
<section id="evaluating-assumptions" class="level1">
<h1>Evaluating Assumptions</h1>
<p>If we were adopting a “final model”, the empirical evidence would support adopting Model 4. It is always important to evaluate any adopted final models’ assumptions.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create residual plots</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residual_plots</span>(lm<span class="fl">.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-residuals-linear" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Two residual plots for Model 4.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuals-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-likelihood-evidence_files/figure-html/fig-residuals-linear-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" alt="Two residual plots for Model 4.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuals-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Two residual plots for Model 4.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Based on the density plot, the assumption of normality looks reasonably met. The scatterplot suggests the assumption that the average residual is 0 is generally met—the loess smoother suggests the average residual is close to 0 at all fitted values. The homoscadasticity assumption also seems reasonable with the range of residuals generally being constant across the different fitted values. Lastly, since the sample is a random sample of Americans, the independence assumption also seems tenable.</p>
</section>
<section id="presenting-the-results-from-the-lrts" class="level1">
<h1>Presenting the Results from the LRTs</h1>
<p>Below we present a table summarizing the results of the likelihood ratio tests.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up data</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison =</span> <span class="fu">c</span>(<span class="st">"Model 0 vs. Model 1"</span>, <span class="st">"Model 2 vs. Model 3"</span>, <span class="st">"Model 3 vs. Model 4"</span>),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">chi =</span> <span class="fu">c</span>(<span class="st">"$$</span><span class="sc">\\</span><span class="st">chi^2(1) = 12.66$$"</span>, <span class="st">"$$</span><span class="sc">\\</span><span class="st">chi^2(1) = 8.92$$"</span>, <span class="st">"$$</span><span class="sc">\\</span><span class="st">chi^2(1) = 5.15$$"</span>),</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fu">c</span>(<span class="st">"&lt;.001"</span>, <span class="st">".003"</span>, <span class="st">".023"</span>)</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>d <span class="sc">|&gt;</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">comparison =</span> <span class="fu">md</span>(<span class="st">"*Model Comparison*"</span>),</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">chi =</span> <span class="st">"LRT Result"</span>,</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">md</span>(<span class="st">"*p*"</span>)</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(comparison),</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"left"</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(chi, p),</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"center"</span></span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.width =</span> <span class="fu">pct</span>(<span class="dv">60</span>)</span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-model-likelihood" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-likelihood-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Results from a set of likelihood ratio tests (LRT) to compare sets of nested candidate models.
</figcaption>
<div aria-describedby="tbl-model-likelihood-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="iofgwvtprx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#iofgwvtprx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#iofgwvtprx thead, #iofgwvtprx tbody, #iofgwvtprx tfoot, #iofgwvtprx tr, #iofgwvtprx td, #iofgwvtprx th {
  border-style: none;
}

#iofgwvtprx p {
  margin: 0;
  padding: 0;
}

#iofgwvtprx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 60%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#iofgwvtprx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#iofgwvtprx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iofgwvtprx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iofgwvtprx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iofgwvtprx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iofgwvtprx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iofgwvtprx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#iofgwvtprx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#iofgwvtprx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#iofgwvtprx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#iofgwvtprx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#iofgwvtprx .gt_spanner_row {
  border-bottom-style: hidden;
}

#iofgwvtprx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#iofgwvtprx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#iofgwvtprx .gt_from_md > :first-child {
  margin-top: 0;
}

#iofgwvtprx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iofgwvtprx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iofgwvtprx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#iofgwvtprx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#iofgwvtprx .gt_row_group_first td {
  border-top-width: 2px;
}

#iofgwvtprx .gt_row_group_first th {
  border-top-width: 2px;
}

#iofgwvtprx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iofgwvtprx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#iofgwvtprx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#iofgwvtprx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iofgwvtprx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iofgwvtprx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iofgwvtprx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#iofgwvtprx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#iofgwvtprx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iofgwvtprx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iofgwvtprx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iofgwvtprx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iofgwvtprx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iofgwvtprx .gt_left {
  text-align: left;
}

#iofgwvtprx .gt_center {
  text-align: center;
}

#iofgwvtprx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iofgwvtprx .gt_font_normal {
  font-weight: normal;
}

#iofgwvtprx .gt_font_bold {
  font-weight: bold;
}

#iofgwvtprx .gt_font_italic {
  font-style: italic;
}

#iofgwvtprx .gt_super {
  font-size: 65%;
}

#iofgwvtprx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#iofgwvtprx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#iofgwvtprx .gt_indent_1 {
  text-indent: 5px;
}

#iofgwvtprx .gt_indent_2 {
  text-indent: 10px;
}

#iofgwvtprx .gt_indent_3 {
  text-indent: 15px;
}

#iofgwvtprx .gt_indent_4 {
  text-indent: 20px;
}

#iofgwvtprx .gt_indent_5 {
  text-indent: 25px;
}

#iofgwvtprx .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#iofgwvtprx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="comparison" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><em>Model Comparison</em></th>
<th id="chi" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">LRT Result</th>
<th id="p" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><em>p</em></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="comparison">Model 0 vs. Model 1</td>
<td class="gt_row gt_center" headers="chi">$$\chi^2(1) = 12.66$$</td>
<td class="gt_row gt_center" headers="p">&lt;.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="comparison">Model 2 vs. Model 3</td>
<td class="gt_row gt_center" headers="chi">$$\chi^2(1) = 8.92$$</td>
<td class="gt_row gt_center" headers="p">.003</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="comparison">Model 3 vs. Model 4</td>
<td class="gt_row gt_center" headers="chi">$$\chi^2(1) = 5.15$$</td>
<td class="gt_row gt_center" headers="p">.023</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<!-- ```{r} -->
<!-- #| results: asis -->
<!-- #| code-fold: true -->
<!-- # Load library -->
<!-- library(texreg) -->
<!-- # Create the table -->
<!-- htmlreg( -->
<!--   l = list(lm.0, lm.1, lm.2, lm.3, lm.4), -->
<!--   stars = numeric(0),    #No p-value stars -->
<!--   digits = 3, -->
<!--   padding = 20,          #Add space around columns (you may need to adjust this via trial-and-error) -->
<!--   include.adjrs = FALSE, #Omit Adjusted R^2 -->
<!--   include.nobs = FALSE,  #Omit sample size -->
<!--   include.rmse = TRUE,   #Include RMSE -->
<!--   custom.model.names = c("Model 0", "Model 1", "Model 2", "Model 3", "Model 4"), -->
<!--   custom.coef.names = c("Intercept", "News Exposure", -->
<!--                         "Education (in years)", "Male", -->
<!--                         "Political Engagement", -->
<!--                         "Education x News Exposure"), -->
<!--   custom.note = "Note. Male, is a dummy-coded predictors. The reference group is non-males.", -->
<!--   reorder.coef = c(2:6, 1), #Put intercept at bottom of table -->
<!--   custom.gof.rows = list( -->
<!--     `ln(Likelihood)` = c(-448.09, -441.76, -417.93, -413.92, -411.33) -->
<!--   ), -->
<!--   reorder.gof = c(3, 2, 1), -->
<!--   caption.above = TRUE, #Move caption above table -->
<!--   inner.rules = 1, #Include line rule before model-level output -->
<!--   outer.rules = 1,  #Include line rules around table -->
<!--   caption = "Table 2: Coefficients (and standard errors) for five models evaluating predictors of news knowledge." -->
<!--   ) -->
<!-- ``` -->
<p><br></p>
</section>
<section id="reporting-individual-predictors-from-a-model" class="level1">
<h1>Reporting Individual Predictors From a Model</h1>
<p>It is also good practice to report the coefficient-level and model-level estimates from any adopted models in a regression table. We will report results from Model 4. At the coefficient-level, the coefficients and standard errors can be reported from the <code>tidy()</code> output. However, since we are using a likelihood framework, the <em>p</em>-values from the <code>tidy()</code> output are incorrect! We need to compute and report likelihood-based <em>p</em>-values.</p>
<p>For example, to evaluate the effect of education on news knowledge we would essentially want to test the hypothesis that:</p>
<p><span class="math display">\[
H_0: \beta_{\mathrm{Education}} = 0
\]</span></p>
<p>To do this with a LRT, we need to compare two models:</p>
<ul>
<li>One model that includes all of the predictors from Model 4;</li>
<li>One model that includes everything from Model 4 <em>except</em> the effect of education.</li>
</ul>
<p>The only difference between these two models is the inclusion of the effect of education in the second model. That means any additional empirical support for the second model over the first is completely due to the effect of education. And, because the second model is nested in the first, we can evaluate this via a LRT.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit full model 4</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model without education</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_education <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Carry out LRT</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_education, lm<span class="fl">.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-421.0504","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"14.6211","5":"0.0001314344","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The <em>p</em>-value associated with the test of whether or not there is an effect of education (at least for the main effect) is 0.0001314. We will need to obtain the likelihood-based <em>p</em>-value for all of the other effects in a similar way. We will</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect of male</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_male <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_male, lm<span class="fl">.4</span>) <span class="co"># Carry out LRT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-420.1399","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"12.8001","5":"0.0003465999","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect of engagement</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_engage <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_engage, lm<span class="fl">.4</span>) <span class="co"># Carry out LRT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-422.7097","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"17.9397","5":"0.00002280146","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect of new exposure (main-effect)</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_news <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_news, lm<span class="fl">.4</span>) <span class="co"># Carry out LRT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-417.4638","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"7.447874","5":"0.006351141","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect of interaction</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_interaction <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news, <span class="at">data =</span> pew)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_interaction, lm<span class="fl">.4</span>) <span class="co"># Carry out LRT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-416.3151","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"5.150592","5":"0.02323844","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intercept</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">lm</span>(knowledge <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.4</span>_intercept <span class="ot">=</span> <span class="fu">lm</span>(knowledge<span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> education <span class="sc">+</span> male <span class="sc">+</span> engagement <span class="sc">+</span> news <span class="sc">+</span> news<span class="sc">:</span>education, <span class="at">data =</span> pew)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(lm<span class="fl">.4</span>_intercept, lm<span class="fl">.4</span>) <span class="co"># Carry out LRT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["#Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["LogLik"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Chisq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>Chisq)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"6","2":"-419.4307","3":"NA","4":"NA","5":"NA","_rn_":"1"},{"1":"7","2":"-413.7398","3":"1","4":"11.38177","5":"0.0007416852","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>We can then replace the <em>p</em>-values from the <code>tidy()</code> output with these likelihood-based <em>p</em>-values. Also, since these <em>p</em>-values are based on chi-squared (not a <em>t</em>-value), we should replace the <em>t</em>-values from the <code>tidy()</code> output with the <span class="math inline">\(\chi^2\)</span>-values from the LRTs.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm<span class="fl">.4</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">c</span>(<span class="fl">11.38</span>, <span class="fl">14.62</span>, <span class="fl">12.80</span>, <span class="fl">17.94</span>, <span class="fl">7.45</span>, <span class="fl">5.15</span>),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> <span class="fu">c</span>(<span class="fl">0.0007417</span>, <span class="fl">0.0001314</span>, <span class="fl">0.0003466</span>, <span class="fl">0.0000228</span>, <span class="fl">0.006351</span>, <span class="fl">0.02324</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["std.error"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["statistic"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"-80.79275198","3":"24.00097198","4":"11.38","5":"0.0007417"},{"1":"education","2":"6.44386100","3":"1.67503584","4":"14.62","5":"0.0001314"},{"1":"male","2":"11.30181648","3":"3.15450924","4":"12.80","5":"0.0003466"},{"1":"engagement","2":"0.39102447","3":"0.09098368","4":"17.94","5":"0.0000228"},{"1":"news","2":"1.17481946","3":"0.43576708","4":"7.45","5":"0.0063510"},{"1":"education:news","2":"-0.06632443","3":"0.02975534","4":"5.15","5":"0.0232400"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>If we were reporting this for publication, we could round the <em>p</em>-values to three decimal places. We would also want to indicate that these are likelihood-based <em>p</em>-values, and that the LRT is based on 1 <em>df</em>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary) <span class="co"># for formatting p-values</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm<span class="fl">.4</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">term =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Education-level"</span>, <span class="st">"Male"</span>, <span class="st">"Political engagement"</span>, <span class="st">"News exposure"</span>, <span class="st">"Education-level x News exposure"</span>),</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">c</span>(<span class="fl">11.38</span>, <span class="fl">14.62</span>, <span class="fl">12.80</span>, <span class="fl">17.94</span>, <span class="fl">7.45</span>, <span class="fl">5.15</span>),</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> <span class="fu">style_pvalue</span>(<span class="fu">c</span>(<span class="fl">0.001</span>, <span class="fl">0.0001314</span>, <span class="fl">0.0003466</span>, <span class="fl">0.0000228</span>, <span class="fl">0.006351</span>, <span class="fl">0.02324</span>), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  )  <span class="sc">|&gt;</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">term =</span> <span class="fu">md</span>(<span class="st">"*Predictor*"</span>),</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate =</span> <span class="fu">md</span>(<span class="st">"*B*"</span>),</span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="fu">md</span>(<span class="st">"*SE*"</span>),</span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">"$$</span><span class="sc">\\</span><span class="st">chi^2$$"</span>,</span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> <span class="fu">md</span>(<span class="st">"*p*"</span>)</span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb65-20"><a href="#cb65-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(</span>
<span id="cb65-21"><a href="#cb65-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(term),</span>
<span id="cb65-22"><a href="#cb65-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"left"</span></span>
<span id="cb65-23"><a href="#cb65-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb65-24"><a href="#cb65-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(</span>
<span id="cb65-25"><a href="#cb65-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(estimate, std.error, statistic, p.value),</span>
<span id="cb65-26"><a href="#cb65-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"center"</span></span>
<span id="cb65-27"><a href="#cb65-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb65-28"><a href="#cb65-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(</span>
<span id="cb65-29"><a href="#cb65-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(estimate, std.error),</span>
<span id="cb65-30"><a href="#cb65-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">decimals =</span> <span class="dv">2</span>,</span>
<span id="cb65-31"><a href="#cb65-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">use_seps =</span> <span class="cn">FALSE</span></span>
<span id="cb65-32"><a href="#cb65-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb65-33"><a href="#cb65-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb65-34"><a href="#cb65-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.width =</span> <span class="fu">pct</span>(<span class="dv">70</span>)</span>
<span id="cb65-35"><a href="#cb65-35" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb65-36"><a href="#cb65-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_footnote</span>(</span>
<span id="cb65-37"><a href="#cb65-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">footnote =</span> <span class="fu">md</span>(<span class="st">"Male is a dummy-coded predictor with non-male as the reference group."</span>),</span>
<span id="cb65-38"><a href="#cb65-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">locations =</span>  <span class="fu">cells_body</span>(<span class="at">columns =</span> term, <span class="at">rows =</span> <span class="dv">3</span>)</span>
<span id="cb65-39"><a href="#cb65-39" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-model-4" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Coefficients and standard errors for Model 4. The <span class="math inline">\(\chi^2\)</span> values and <em>p</em>-values are based on likelihood ratio tests (LRT) with 1 degree-of-freedom to evaluate each predictor.
</figcaption>
<div aria-describedby="tbl-model-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="ttcqztrtsc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ttcqztrtsc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ttcqztrtsc thead, #ttcqztrtsc tbody, #ttcqztrtsc tfoot, #ttcqztrtsc tr, #ttcqztrtsc td, #ttcqztrtsc th {
  border-style: none;
}

#ttcqztrtsc p {
  margin: 0;
  padding: 0;
}

#ttcqztrtsc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 70%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ttcqztrtsc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ttcqztrtsc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ttcqztrtsc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ttcqztrtsc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ttcqztrtsc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ttcqztrtsc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ttcqztrtsc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ttcqztrtsc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ttcqztrtsc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ttcqztrtsc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ttcqztrtsc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ttcqztrtsc .gt_spanner_row {
  border-bottom-style: hidden;
}

#ttcqztrtsc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ttcqztrtsc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ttcqztrtsc .gt_from_md > :first-child {
  margin-top: 0;
}

#ttcqztrtsc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ttcqztrtsc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ttcqztrtsc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ttcqztrtsc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ttcqztrtsc .gt_row_group_first td {
  border-top-width: 2px;
}

#ttcqztrtsc .gt_row_group_first th {
  border-top-width: 2px;
}

#ttcqztrtsc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ttcqztrtsc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ttcqztrtsc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ttcqztrtsc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ttcqztrtsc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ttcqztrtsc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ttcqztrtsc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ttcqztrtsc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ttcqztrtsc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ttcqztrtsc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ttcqztrtsc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ttcqztrtsc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ttcqztrtsc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ttcqztrtsc .gt_left {
  text-align: left;
}

#ttcqztrtsc .gt_center {
  text-align: center;
}

#ttcqztrtsc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ttcqztrtsc .gt_font_normal {
  font-weight: normal;
}

#ttcqztrtsc .gt_font_bold {
  font-weight: bold;
}

#ttcqztrtsc .gt_font_italic {
  font-style: italic;
}

#ttcqztrtsc .gt_super {
  font-size: 65%;
}

#ttcqztrtsc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ttcqztrtsc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ttcqztrtsc .gt_indent_1 {
  text-indent: 5px;
}

#ttcqztrtsc .gt_indent_2 {
  text-indent: 10px;
}

#ttcqztrtsc .gt_indent_3 {
  text-indent: 15px;
}

#ttcqztrtsc .gt_indent_4 {
  text-indent: 20px;
}

#ttcqztrtsc .gt_indent_5 {
  text-indent: 25px;
}

#ttcqztrtsc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ttcqztrtsc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><em>Predictor</em></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><em>B</em></th>
<th id="std.error" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><em>SE</em></th>
<th id="statistic" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">$$\chi^2$$</th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><em>p</em></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="term">Intercept</td>
<td class="gt_row gt_center" headers="estimate">−80.79</td>
<td class="gt_row gt_center" headers="std.error">24.00</td>
<td class="gt_row gt_center" headers="statistic">11.38</td>
<td class="gt_row gt_center" headers="p.value">0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Education-level</td>
<td class="gt_row gt_center" headers="estimate">6.44</td>
<td class="gt_row gt_center" headers="std.error">1.68</td>
<td class="gt_row gt_center" headers="statistic">14.62</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">Male<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></td>
<td class="gt_row gt_center" headers="estimate">11.30</td>
<td class="gt_row gt_center" headers="std.error">3.15</td>
<td class="gt_row gt_center" headers="statistic">12.80</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Political engagement</td>
<td class="gt_row gt_center" headers="estimate">0.39</td>
<td class="gt_row gt_center" headers="std.error">0.09</td>
<td class="gt_row gt_center" headers="statistic">17.94</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="term">News exposure</td>
<td class="gt_row gt_center" headers="estimate">1.17</td>
<td class="gt_row gt_center" headers="std.error">0.44</td>
<td class="gt_row gt_center" headers="statistic">7.45</td>
<td class="gt_row gt_center" headers="p.value">0.006</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">Education-level x News exposure</td>
<td class="gt_row gt_center" headers="estimate">−0.07</td>
<td class="gt_row gt_center" headers="std.error">0.03</td>
<td class="gt_row gt_center" headers="statistic">5.15</td>
<td class="gt_row gt_center" headers="p.value">0.023</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="5" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Male is a dummy-coded predictor with non-male as the reference group.</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="references" class="level1">




</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Cohen:1994" class="csl-entry" role="listitem">
Cohen, J. (1994). The earth is round (<span class="math inline">\(p &lt; .05\)</span>). <em>American Psychologist</em>, <em>49</em>(12), 997–1003.
</div>
<div id="ref-Johansson:2011" class="csl-entry" role="listitem">
Johansson, T. (2011). Hail the impossible: P-values, evidence, and likelihood. <em>Scandinavian Journal of Psychology</em>, <em>52</em>, 113–125. <a href="https://doi.org/10.1111/j.1467-9450.2010.00852.x">https://doi.org/10.1111/j.1467-9450.2010.00852.x</a>
</div>
<div id="ref-Johnstone:1986" class="csl-entry" role="listitem">
Johnstone, D. J. (1986). Tests of significance in theory and practice. <em>The Statistician</em>, <em>35</em>, 491–504.
</div>
<div id="ref-Mosteller:1954" class="csl-entry" role="listitem">
Mosteller, F., &amp; Bush, R. B. (1954). Selected quantitative techniques. In G. Lindzey (Ed.), <em>Handbook of social psychology</em> (pp. 289–334). Addison-Wesley.
</div>
<div id="ref-Weakliem:2016" class="csl-entry" role="listitem">
Weakliem, D. L. (2016). <em>Hypothesis testing and model selection in the social sciences</em>. The Guilford Press.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Sometimes this is also referred to a the sum of squared errors (SSE).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is in some sense mixing the paradigms of likelihood-based evidence and classical hypothesis test-based evidence. In a future set of notes we will learn about information criteria which eliminate the need to mix these two paradigms.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The use of the term “residual deviance” is not universal. Some textbooks omit the “residual” part and just refer to it as the “deviance”. Others use the term “model deviance”.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>