---
title: "Update and Install Tech"
format:
  html:
   css: "../assets/sticky-notes.css"
date: "today"
---

Before next class, update R, RStudio, and all of your packages!

- [Update R](https://www.r-project.org/) to the most recent version (v. 4.4.2; Pile of Leaves). You can check your current version by typing `R.version` into the console.
- [Update RStudio Desktop](https://posit.co/download/rstudio-desktop/) to the most recent version (v. 2024.09.1+394). You can check your current version by selecting `RStudio > About RStudio`.
- Once you have updated R and RStudio, update all of your R packages (In the `Packages` tab in RStudio click `Update`).


Also, install Quarto.

1.  Head over to <https://quarto.org/> and click on the big, blue "Get Started" button. Then follow the instructions to install Quarto.
2.  Open RStudio. (Note if RStudio was open when you installed Quarto, quit and re-open it.) At this point in RStudio, if you go to `File > New File...` you should see options to choose `Quarto Document` and `Quarto Presentation`.


<br /><br />

:::fyi
When you have updated R, RStudio, and your packages, and you have successfully installed Quarto, please show Andy in class or send him screenshots of (1) your R version (when you open RStudio), (2) your RStudio version (click "About RStudio"), and (3) your Quarto version (click the "Terminal" tab and type "quarto check")
:::



<br />



