---
title: "Introduction to Quarto"
format:
  html:
   css: "../assets/sticky-notes.css"
date: "today"
---

Before next class install Quarto.

1.  Head over to <https://quarto.org/> and click on the big, blue "Get Started" button. Then follow the instructions to install Quarto.
2.  Open RStudio. (Note if RStudio was open when you installed Quarto, quit and re-open it.) At this point in RStudio, if you go to `File > New File...` you should see options to choose `Quarto Document` and `Quarto Presentation`.
3. Work through the [Hello Quarto Tutorial](https://quarto.org/docs/get-started/hello/rstudio.html). This will introduce you to some of the basic concepts of creating and rendering a Quarto document. Click the link on the left-side of the "Getting Started" page. Make sure that the RStudio tool is selected at the top of the tutorial.
4. Work through the [Computations Tutorial](https://quarto.org/docs/get-started/computations/rstudio.html) to learn how to integrate R syntax into your Quarto document. Again, before starting, ensure that the RStudio tool is selected at the top of the tutorial.


<br />


## Learn More

Check out the Welcome to Quarto Workshop. This is a 2 1/2 hour workshop introducing people to Quarto.

- [Welcome to Quarto Workshop! (YouTube Video)](https://www.youtube.com/watch?v=yvi5uXQMvu4)


If you are familiar with RMarkdown and want to learn how to switch over to Quarto, here is a nice 30 minute talk by Mine Çetinkaya-Rundel that helps you do that.

- [2022 Toronto Workshop on Reproducibility - Mine Çetinkaya-Rundel (YouTube Video)](https://www.youtube.com/watch?v=6p4vOKS6Xls)







